name: Deploy Foo api Lambda
on:
  push:
    paths:
      - "api/foo/**"
jobs:
  deploy:
    strategy:
        matrix:
          node-version: [12.x]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: cd api/foo
    - name: build
      run: |
        pwd
    - name: zip
      uses: montudor/action-zip@v0.1.0
      with:
        args: zip -r foo-api.zip node_modules/ index.js  
    - name: Check zip file
      run: |
        echo | ls -ltr
