name: Deploy Foo api Lambda
on:
  push:
    paths:
      - "api/foo/**"
jobs:
  deploy:
    strategy:
        matrix:
          node-version: [12.x]
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: api/foo
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: build
      run: |
        npm install
    - name: zip
      uses: thedoctor0/zip-release@master
      with:
        filename: 'foo-api.zip'
        exclusions: 'package.json package-local.json'
        directory: 'api/foo'
    - name: Check zip file
      run: |
        ls -ltr
